### ISSUE TITLE
Is this different with the original caffe's conv_layer.cpp?

### ISSUE THREAD

**Issue by lyk125** [yonghenglh6/DepthwiseConvolution#1]
Hi,I campare your depthwise_conv_layer.cpp with original caffe's conv_layer.cpp:except the layer name,all other is the same.Is that true?

Please forgive me for being impolite.

**Comment by yonghenglh6** [comment]
2333   
You are right. The cu file is the only one I modified. 
The original gpu forward-backward is so slow that I re-implement it, while the original cpu's implement is fast enough so I am not changing it.
If you want a more efficient implement of this, you may be interested in this:
https://github.com/sp2823/caffe/blob/convolution-depthwise/src/caffe/layers/conv_dw_layer.cu
This implement is about one fifth faster than mine.
