### ISSUE TITLE
Why slower than tensorflow

### ISSUE THREAD

**Issue by twmht** [yonghenglh6/DepthwiseConvolution#16]
In Mobilenet-tensorflow (https://github.com/Zehaos/MobileNet), The speed in GTX-1080 is only 3ms, but caffe takes 8ms. 

What makes the difference between caffe and tensorflow?

thanks

**Comment by yonghenglh6** [comment]
This implement is a temporary patch in origin caffe, so the speed is not the fastest.
My code is naive, which just make up the serial-process-order bug between groups in origin caffe and give us the ability to train the net.
The difference is so big that I cannot estimate it.
