### ISSUE TITLE
how to change the two super-parameters ?And, trian time

### ISSUE THREAD

**Issue by Ai-is-light** [yonghenglh6/DepthwiseConvolution#17]
how to change the two super-parameters ?and, why the train time  of depth-wise convolution is longer than the same out number of convolution?

**Comment by Ai-is-light** [comment]
@yonghenglh6 the time of  GPUPerformance on example net in your repository is the train time or the test time? Thanks for your excellent work

**Comment by yonghenglh6** [comment]
which two parameters?  The parameter usage is same as original conv's, except the group num which must be set to input channel.
Please assure the group number is set both in two nets. This implement is a temporary patch in origin caffe, so the speed is not the fastest.
The time I post consist of both forward and backward time, which is same between train and test.

**Comment by Ai-is-light** [comment]
@yonghenglh6 Thanks for your answer and your good work. I have the other question about the time. The time you post is really faster, however, is there any other setting in the prototxt , like the https://github.com/shicai/MobileNet-Caffe/issues/13 , and setting the egine:CAFFE in the convolution layer of the train.prototxt. I'm really confused about the speed , although I follow the work of you, I can't really accelerate the train speed. I even observed the time of DepthWIseConvolution is more consuming than the normal Convolution at the same input, output, the kernel size,padding setting and stride. I wonder whether is different setting about the GPU or others? Thanks, any suggestion is needed and welcome

**Comment by Ai-is-light** [comment]
The two parameters, I mean the width multiplier and the resolution multiplier. we have to set them by hand?

**Comment by yonghenglh6** [comment]
"I even observed the time of DepthWIseConvolution is more consuming than the normal Convolution at the same input, output, the kernel size,padding setting and stride."
Have you set the group param to input channel in both net?

**Comment by Ai-is-light** [comment]
no , I just set the group for the DepthWise convolution in the mobileNet, and in the VGG, I just use the convolution and not set the group in the prototxt

**Comment by Ai-is-light** [comment]
would you mind share your caffe, GPU, cudnn's type?Thanks

**Comment by yonghenglh6** [comment]
caffe: origingpu: 1080
cudnn: 5.1
 
 
------------------ 原始邮件 ------------------
发件人: "Yong"; 
发送时间: 2018年1月16日(星期二) 上午10:04
收件人: "yonghenglh6/DepthwiseConvolution"; 
抄送: "yonghenglh6"; "Mention"; 
主题: Re: [yonghenglh6/DepthwiseConvolution] how to change the twosuper-parameters ?And, trian time (#17)

 


would you mind share your caffe, GPU, cudnn's type?Thanks
 
&mdash;

**Comment by Ai-is-light** [comment]
Hey, I used the caffe time to test the time of the VGG-19, moblieNet and your works. Your work does really work well.
input(224,224),1000classes # mini-batch=5   SoftmaxWithLoss |  
 | Ave forward/ms | Ave backward/ms | f-b   total/ms
  VGG-19 | 40.5399 | 80.7256 | 121.335
  | depth-wise mobileNet | 47.7849 | 56.7849 | 104.474
  | mobileNet-original | 167.109 | 373.929 | 514.118

**Comment by Ai-is-light** [comment]
caffe:CMU; gpu:Tesla M40;cuda:8.0;cudnn:5.1

**Comment by yonghenglh6** [comment]
Thank you
