### ISSUE TITLE
error == cudaSuccess (77 vs. 0 ) an illegal memory access was encountered

### ISSUE THREAD

**Issue by Ai-is-light** [yonghenglh6/DepthwiseConvolution#18]
Did someone meet the problem ,called error == cudaSuccess (77 vs. 0 ) , when I changed the original convolution to the format of the depthwise convolution,and run it , I got the math_functions.cuL79 ] check failed: error == cudaSuccess (77 vs. 0 ) an illegal memory access was encountered. However, when I used the CAFFE TIME to test the same prototxt(the depthwise convolution prototxt), it worked and cumulated the network's time. @ @yonghenglh6 Thanks

**Comment by yonghenglh6** [comment]
It seems there is a error for backward func in train phrase.
Would you post your prototxt file?

**Comment by Ai-is-light** [comment]
thanks. but the prototxt is in the intranet. I'm confused, when I use 1 GPU， it can ran,however try 2*GPUs or 4 GPUs , it's wrong.

**Comment by yonghenglh6** [comment]
alright.
You may check caffe test command to get more info,  assure this does not happen in origin net, and assure the group num param is set to input channel in your new net.
Otherwise, I have no more idea...

**Comment by Ai-is-light** [comment]
Thx
