### ISSUE TITLE
Dose the restriction 'only for stride1' still hold?

### ISSUE THREAD

**Issue by kfxw** [yonghenglh6/DepthwiseConvolution#20]
Thanks for your code and sharing.
In the very beginning lines in .cu file there are some notes saying
```
/*
 * The depthwise layer for mobilenet.   only for stride 1
 */
```
However when I quickly look through the code, the case 'stride != 1' seems to be already considered and handled.
In case of some errors, I'm writing to ask whether I can use stride>1 in this layer now?
Thanks!

**Comment by yonghenglh6** [comment]
All strides has been implemented.
Thanku for remanding.

**Comment by BrandonJoffe** [comment]
Hey @yonghenglh6,

thanks for sharing!

I've been doing some testing and found that the gradient being back propagated using a stride of 2 does not match the gradient using a standard convolution with same the parameters. 

I'm not sure if this is something you have tested?
