### ISSUE TITLE
why your deploy not have batch_norm_param { use_global_stats: true}???

### ISSUE THREAD

**Issue by Ai-is-light** [yonghenglh6/DepthwiseConvolution#21]
in https://github.com/shicai/MobileNet-Caffe/blob/master/mobilenet_deploy.prototxt#L50 
batch_norm_param {
    use_global_stats: true

why  your deploy not have batch_norm_param { use_global_stats: true}???
@yonghenglh6 Thanks

**Comment by yonghenglh6** [comment]
The default behavior of the param is being true on training and being false on testing.
