### ISSUE TITLE
Except for the speed, does it  perform  like the original caffe convolution?

### ISSUE THREAD

**Issue by jiangyangzhou** [yonghenglh6/DepthwiseConvolution#28]
I know it can run faster than original conv, but I find all the params are available in original caffe convolution, so if I just replace DepthwiseConvolution with Convolution, do they have same performance?
Or if depthwiseConvolution does something else?
Thanks very much

**Comment by yonghenglh6** [comment]
The param's meaning is same as original conv because mycode inherits the cpu part from it.  
There is only one difference that depthwise-conv 'group' param must be set to input channel.
