### ISSUE TITLE
 Unknown layer type: DepthwiseConvolution

### ISSUE THREAD

**Issue by firefox1031** [yonghenglh6/DepthwiseConvolution#7]
Hello, I added your .hpp/.cpp/.cu files to my caffe folders accordingly and compiled successfully(I didn't modify any other files). But when I try to train my mobilenet model, it always prompted " Unknown layer type: DepthwiseConvolution". Could you please tell me where the problem is? By the way, my caffe runs on windows 7.

**Comment by yonghenglh6** [comment]
I'm sorry for not knowing a thing about windows-caffe.
Have you ever tried add any other customed layer before?

**Comment by firefox1031** [comment]
No, this is my first time to add a customed layer. I have completely no idea why this error occured.

**Comment by yonghenglh6** [comment]
any progression?

**Comment by firefox1031** [comment]
yes, I compiled it successfully
