### ISSUE TITLE
Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: DepthwiseConvolution

### ISSUE THREAD

**Issue by walegahaha** [yonghenglh6/DepthwiseConvolution#8]
I use the latest version of caffe
Just copy three files and make?
Do I need to modify caffe.proto and layer_factory.cpp?

**Comment by walegahaha** [comment]
Solved！
in your examples, change all the {{type: "DepthwiseConvolution"}} to {{type: "ConvolutionDepthwise"}}

**Comment by yonghenglh6** [comment]
"change all the {{type: "DepthwiseConvolution"}} to {{type: "ConvolutionDepthwise"}}" is not the right solution.
I guess you have tried other depthwise convolution implement (etc. https://github.com/BVLC/caffe/pull/5665/files) before. So your operations will activate their implement.
"Unknown layer type" means your files are not put on suitable place, or you forgot to re cmake in your build folder if you use cmake.
You may check it.

**Comment by walegahaha** [comment]
Sorry, I've made a mistake
I use your prototxt and their implement
