### ISSUE TITLE
the solver.prototxt

### ISSUE THREAD

**Issue by andeyeluguo** [yonghenglh6/DepthwiseConvolution#9]
Can you share your solver.prototxt ?
I only get 43% val acc when the epoch is 200000.
Mine is 
net: "train_val.prototxt"
test_initialization: false
test_iter: 100
test_interval: 5000
display: 100
average_loss: 40
base_lr: 0.01
lr_policy: "poly"
power: 1.0
max_iter: 1000000
momentum: 0.9
weight_decay: 0.0001
snapshot: 5000
snapshot_prefix: "models/mobilenet"

**Comment by yonghenglh6** [comment]
Please check the train accuracy of the net in
https://github.com/shicai/MobileNet-Caffe.
I can only assure there is no calculation error compared with origin caffe.

It seems the lr_policy keeps your learning rate still large when 200000 epoch.  Have u ever tried a little max_iter?
